let gamesList = [
    { name: 'valorant', image: '../assets/images/valorant.jpeg', storage: '50 GB', desc: '"Valorant" is a tactical first-person shooter (FPS) game developed and published by Riot Games, released in 2020. Set in a near-future Earth, it pits two teams of five players against each other: attackers, who plant a bomb called the Spike, and defenders, who try to stop them. The game features a diverse cast of characters, called "agents," each with unique abilities that can be used strategically to gain an advantage in combat or support the team. Matches are fast-paced and require a mix of precise shooting skills, map knowledge, and teamwork. With its blend of tactical gameplay and character-based abilities, Valorant has gained popularity as a competitive esports title.', trailerLink: 'https://www.youtube.com/watch?v=e_E9W2vsRbQ', downLink: '[Blank]' },
    { name: 'call of duty MF-3', image: '../assets/images/Callofduty.jpeg', storage: '100 GB', desc: 'Call of Duty: Modern Warfare III is a 2023 first-person shooter video game developed by Sledgehammer Games and published by Activision. It is a sequel to 2022\'s Modern Warfare II, serving as the third entry in the rebooted Modern Warfare sub-series and the twentieth installment in the overall Call of Duty series. The game was released on November 10, 2023, for PlayStation 4, PlayStation 5, Windows, Xbox One, and Xbox Series X/S.', trailerLink: 'https://www.youtube.com/watch?v=mHDEDDrGYvo', downLink: '[Blank]' },
    { name: 'phasmophobia', image: '../assets/images/Phasmophobia.jpeg', storage: '20 GB', desc: 'Phasmophobia is a paranormal horror game by British indie game studio Kinetic Games. The game became available in early access for Microsoft Windows with virtual reality support in September 2020. In the game, one to four players work to complete a contract where they must identify the type of ghost haunting a designated site. It is based on the popular hobby of ghost hunting.', trailerLink: 'https://www.youtube.com/watch?v=pQ3SlgA9R7k', downLink: '[Blank]' },
    { name: 'apex legends', image: '../assets/images/apex.jpeg', storage: '60 GB', desc: 'Apex Legends is a free-to-play battle royale game developed by Respawn Entertainment and published by Electronic Arts. It features squads of three players competing in a last-team-standing match within an ever-shrinking safe zone.', trailerLink: 'https://www.youtube.com/watch?v=oQtHENM_GZU', downLink: '[Blank]' },
    { name: 'overwatch', image: '../assets/images/overwatch.jpg', storage: '30 GB', desc: 'Overwatch is a team-based multiplayer first-person shooter developed and published by Blizzard Entertainment. Players choose from a diverse cast of heroes, each with their own unique abilities, and work together to secure objectives.', trailerLink: 'https://www.youtube.com/watch?v=FqnKB22pOC0', downLink: '[Blank]' },
    { name: 'counter-strike: global offensive', image: '../assets/images/csgo.jpeg', storage: '20 GB', desc: 'Counter-Strike: Global Offensive is a multiplayer first-person shooter developed by Valve and Hidden Path Entertainment. It features classic gameplay modes such as bomb defusal and hostage rescue, requiring teamwork and strategy.', trailerLink: '', downLink: '[Blank]' },
    { name: 'rainbow six siege', image: '../assets/images/rainbow.jpeg', storage: '60 GB', desc: 'Tom Clancy\'s Rainbow Six Siege is a tactical shooter game developed by Ubisoft. It emphasizes environmental destruction and cooperation between players, with each match focusing on sieges between two teams.', trailerLink: '', downLink: '[Blank]' },
    { name: 'call of duty: warzone', image: '../assets/images/cod.jpeg', storage: '100 GB', desc: 'Call of Duty: Warzone is a free-to-play battle royale game developed by Infinity Ward and Raven Software, published by Activision. It features a large map, allowing for up to 150 players in a match, with various game modes.', trailerLink: 'https://www.youtube.com/watch?v=U3wR3iFa3Rg', downLink: '[Blank]' },
    { name: 'paladins', image: '../assets/images/paladins.jpeg', storage: '20 GB', desc: 'Paladins is a free-to-play hero shooter developed and published by Hi-Rez Studios. It offers a wide variety of champions, each with their own unique abilities, and multiple game modes, including siege and team deathmatch.', trailerLink: 'https://www.youtube.com/watch?v=2tohJxalceE', downLink: '[Blank]' },
    { name: 'destiny 2', image: '../assets/images/destiny.jpg', storage: '105 GB', desc: 'Destiny 2 is a free-to-play online-only multiplayer first-person shooter developed by Bungie. It combines elements from traditional shooters with MMO and RPG elements, featuring both player versus environment and player versus player modes.', trailerLink: 'https://www.youtube.com/watch?v=9mbdyCw4QeA', downLink: '[Blank]' },
    { name: 'team fortress 2', image: '../assets/images/teamfortress.jpg', storage: '20 GB', desc: 'Team Fortress 2 is a multiplayer first-person shooter developed and published by Valve. It offers a variety of game modes, including capture the flag and king of the hill, with a distinct art style and humorous tone.', trailerLink: 'https://www.youtube.com/watch?v=AXDIXqBQkEI', downLink: '[Blank]' },
    { name: 'splitgate: arena warfare', image: '../assets/images/split.jpg', storage: '15 GB', desc: 'Splitgate: Arena Warfare is a free-to-play multiplayer first-person shooter developed and published by 1047 Games. It combines elements of classic arena shooters with portal mechanics, allowing players to create portals to outmaneuver opponents.', trailerLink: 'https://www.youtube.com/watch?v=gE3Wd3zAhcM', downLink: '[Blank]' },
    { name: 'warframe', image: '../assets/images/warframe.jpeg', storage: '25 GB', desc: 'Warframe is a free-to-play cooperative third-person shooter developed and published by Digital Extremes. Players control members of the Tenno, a race of ancient warriors who have awoken from centuries of cryosleep to find themselves at war in a planetary system.', trailerLink: 'https://www.youtube.com/watch?v=0vuJitrbTFY', downLink: '[Blank]' },
    { name: 'battlefield V', image: '../assets/images/battlefield.jpeg', storage: '50 GB', desc: 'Battlefield V is a first-person shooter video game developed by EA DICE and published by Electronic Arts. It is the sixteenth installment in the Battlefield series, set during World War II, where players engage in large-scale battles with various weapons and vehicles.', trailerLink: 'https://www.youtube.com/watch?v=Y6ZjY5qL1_Q', downLink: '[Blank]' },
    { name: 'gears 5', image: '../assets/images/gears.jpeg', storage: '80 GB', desc: 'Gears 5 is a third-person shooter game developed by The Coalition and published by Xbox Game Studios. It is the sixth installment of the Gears of War series, featuring intense action, cooperative gameplay, and a compelling story set in a post-apocalyptic world.', trailerLink: 'https://www.youtube.com/watch?v=Nyv3GjM_VFQ', downLink: '[Blank]' },
    { name: 'borderlands 3', image: '../assets/images/borderlands.jpeg', storage: '75 GB', desc: 'Borderlands 3 is a first-person shooter action role-playing game developed by Gearbox Software. Players embark on a journey through the chaotic world of Pandora and beyond, exploring new planets, encountering diverse enemies, and collecting loot.', trailerLink: 'https://www.youtube.com/watch?v=4D9L8wbo9Bs', downLink: '[Blank]' },
    { name: 'DOOM eternal', image: '../assets/images/doom.jpg', storage: '50 GB', desc: 'DOOM Eternal is a first-person shooter game developed by id Software and published by Bethesda Softworks. It is the fifth main game in the Doom series, featuring fast-paced combat against hordes of demons, with an emphasis on mobility and brutal glory kills.', trailerLink: 'https://www.youtube.com/watch?v=qG-X95q5Vjo', downLink: '[Blank]' },
    { name: 'halo: the master chief collection', image: '../assets/images/halo.jpeg', storage: '120 GB', desc: 'Halo: The Master Chief Collection is a compilation of first-person shooter video games in the Halo series developed by 343 Industries and published by Xbox Game Studios. It includes remastered versions of Halo: Combat Evolved, Halo 2, Halo 3, Halo 4, and Halo: Reach, offering players the complete Master Chief saga.', trailerLink: 'https://www.youtube.com/watch?v=q3pEVFVFI68', downLink: '[Blank]' },
    { name: 'titanfall 2', image: '../assets/images/titanfall.jpeg', storage: '50 GB', desc: 'Titanfall 2 is a first-person shooter game developed by Respawn Entertainment and published by Electronic Arts. It features fast-paced multiplayer combat and a captivating single-player campaign, where players control pilots and their powerful Titans in futuristic battles.', trailerLink: 'https://www.youtube.com/watch?v=2ISYN1AshZY', downLink: '[Blank]' },
    { name: 'dying light 2', image: '../assets/images/dyinglight.jpg', storage: '50 GB', desc: 'Dying Light 2 is an upcoming first-person action role-playing game developed by Techland. Set in a vast open-world environment, players navigate through a zombie-infested city, making choices that impact the narrative and gameplay.', trailerLink: 'https://www.youtube.com/watch?v=TYv2PxcB0zc', downLink: '[Blank]' },
    { name: 'left 4 dead 2', image: '../assets/images/left4dead2.jpg', storage: '13 GB', desc: 'Left 4 Dead 2 is a cooperative first-person shooter game developed and published by Valve. Set during a zombie apocalypse, players team up to survive hordes of infected while progressing through levels with various objectives.', trailerLink: 'https://www.youtube.com/watch?v=GUDZg3CzFkw', downLink: '[Blank]' },
    { name: 'battlefront II', image: '../assets/images/battlefront.jpeg', storage: '60 GB', desc: 'Star Wars Battlefront II is an action shooter video game based on the Star Wars franchise. Developed by DICE, Motive Studios, and Criterion Software and published by Electronic Arts, it features both single-player and multiplayer game modes set in the Star Wars universe.', trailerLink: 'https://www.youtube.com/watch?v=ezVfiCU6cJk', downLink: '[Blank]' },
    { name: 'far cry 5', image: '../assets/images/farcry5.jpeg', storage: '50 GB', desc: 'Far Cry 5 is a first-person shooter game developed by Ubisoft Montreal and published by Ubisoft. Set in the fictional Hope County, Montana, players assume the role of a sheriff\'s deputy who must liberate the county from a cult led by the charismatic Joseph Seed.', trailerLink: 'https://www.youtube.com/watch?v=1HWc3YFpM_4', downLink: '[Blank]' },
    { name: 'metro exodus', image: '../assets/images/metro.jpeg', storage: '50 GB', desc: 'Metro Exodus is a first-person shooter game developed by 4A Games and published by Deep Silver. It is the third installment in the Metro video game series, based on the novels by Dmitry Glukhovsky, and follows the story of Artyom as he navigates post-apocalyptic Russia.', trailerLink: 'https://www.youtube.com/watch?v=a39wb5YhZ5Q', downLink: '[Blank]' },
    { name: 'dead by daylight', image: '../assets/images/deadbydaylight.jpeg', storage: '25 GB', desc: 'Dead by Daylight is an asymmetric survival horror game developed by Behaviour Interactive. Players can take on the role of a survivor trying to escape a killer-controlled environment or play as the killer hunting down the survivors.', trailerLink: 'https://www.youtube.com/watch?v=Cj13S4jTc9w', downLink: '[Blank]' },
    { name: 'escape from tarkov', image: '../assets/images/escapefrom.jpeg', storage: '12 GB', desc: 'Escape from Tarkov is a hardcore and realistic online first-person action RPG/Simulator with MMO features and a story-driven walkthrough. Developed by Battlestate Games, players engage in raids in a fictional Russian city torn by warfare.', trailerLink: 'https://www.youtube.com/watch?v=-gj6u7o3QXM', downLink: '[Blank]' },
    { name: 'resident evil village', image: '../assets/images/residentevil.jpeg', storage: '50 GB', desc: 'Resident Evil Village is a survival horror game developed and published by Capcom. It is the tenth major installment in the Resident Evil series, following the story of Ethan Winters as he explores a mysterious village full of grotesque creatures.', trailerLink: 'https://www.youtube.com/watch?v=dRpXEc-EJow', downLink: '[Blank]' },
    { name: 'playerunknown\'s battlegrounds', image: '../assets/images/pubg.jpeg', storage: '30 GB', desc: 'PlayerUnknown\'s Battlegrounds is an online multiplayer battle royale game developed and published by PUBG Corporation. It features up to 100 players parachuting onto an island, scavenging for weapons and equipment to kill others while avoiding getting killed themselves.', trailerLink: 'https://www.youtube.com/watch?v=8yciuwzYb9I', downLink: '[Blank]' },
    { name: 'tom clancy\'s ghost recon breakpoint', image: '../assets/images/tomclancy.jpeg', storage: '50 GB', desc: 'Tom Clancy\'s Ghost Recon Breakpoint is a tactical shooter video game developed by Ubisoft Paris and published by Ubisoft. It is the eleventh installment in the Tom Clancy\'s Ghost Recon franchise and is set in an open-world environment called Auroa.', trailerLink: 'https://www.youtube.com/watch?v=j5yNvcJhrV0', downLink: '[Blank]' },
    { name: 'rust', image: '../assets/images/rust.jpeg', storage: '20 GB', desc: 'Rust is a multiplayer online survival game developed by Facepunch Studios. Players must survive by gathering resources, crafting items, and building shelters while avoiding being killed by other players and hostile creatures.', trailerLink: 'https://www.youtube.com/watch?v=4WTO2xKtomo', downLink: '[Blank]' },
    { name: 'the division 2', image: '../assets/images/thedivision.jpg', storage: '50 GB', desc: 'Tom Clancy\'s The Division 2 is an online action role-playing video game developed by Massive Entertainment and published by Ubisoft. Set in a near-future Washington, D.C., players take on the role of Division agents tasked with helping to rebuild the city after a biological attack.', trailerLink: 'https://www.youtube.com/watch?v=LrhaYSb_qP8', downLink: '[Blank]' },
];
const gamesDBInstance = require("../models/games");

const getGames = (req, res) => {
    // gamesDBInstance.insertMany(gamesList)
    gamesDBInstance
        .find({})
        .then(result => res.json(result))
        .catch(err => {
            console.error('Error fetching games:', err);
            res.status(500).json({ error: 'Internal Server Error' });
        });
}

const searchGame = (req, res) => {
    const game = req.params.game.toLowerCase();

    if (game == "") {
        gamesDBInstance
            .find({})
            .then(result => res.json(result))
            .catch(err => {
                console.error('Error fetching games:', err);
                res.status(500).json({ error: 'Internal Server Error' });
            });
        return;
    }
    gamesDBInstance
        .find({ name: game })
        .then(filteredGamesList => res.json(filteredGamesList[0]))
        .catch(err => {
            console.error(`Error searching ${game} game ${err}`);
            res.status(500).json({ error: 'Internal Server Error' });
        });
}

module.exports = {
    getGames,
    searchGame
}
