let gamesList = [
{ name: 'dying light 2', image: '../assets/images/dyinglight.jpg', storage: '50 GB', desc: 'Dying Light 2 is an upcoming first-person action role-playing game developed by Techland. Set in a vast open-world environment, players navigate through a zombie-infested city, making choices that impact the narrative and gameplay.', trailerLink: 'https://www.youtube.com/watch?v=TYv2PxcB0zc', downLink: '[Blank]' },
{ name: 'left 4 dead 2', image: '../assets/images/left4dead2.jpg', storage: '13 GB', desc: 'Left 4 Dead 2 is a cooperative first-person shooter game developed and published by Valve. Set during a zombie apocalypse, players team up to survive hordes of infected while progressing through levels with various objectives.', trailerLink: 'https://www.youtube.com/watch?v=GUDZg3CzFkw', downLink: '[Blank]' },
{ name: 'battlefront II', image: '../assets/images/battlefront.jpeg', storage: '60 GB', desc: 'Star Wars Battlefront II is an action shooter video game based on the Star Wars franchise. Developed by DICE, Motive Studios, and Criterion Software and published by Electronic Arts, it features both single-player and multiplayer game modes set in the Star Wars universe.', trailerLink: 'https://www.youtube.com/watch?v=ezVfiCU6cJk', downLink: '[Blank]' },
{ name: 'far cry 5', image: '../assets/images/farcry5.jpeg', storage: '50 GB', desc: 'Far Cry 5 is a first-person shooter game developed by Ubisoft Montreal and published by Ubisoft. Set in the fictional Hope County, Montana, players assume the role of a sheriff\'s deputy who must liberate the county from a cult led by the charismatic Joseph Seed.', trailerLink: 'https://www.youtube.com/watch?v=1HWc3YFpM_4', downLink: '[Blank]' },
{ name: 'metro exodus', image: '../assets/images/metro.jpeg', storage: '50 GB', desc: 'Metro Exodus is a first-person shooter game developed by 4A Games and published by Deep Silver. It is the third installment in the Metro video game series, based on the novels by Dmitry Glukhovsky, and follows the story of Artyom as he navigates post-apocalyptic Russia.', trailerLink: 'https://www.youtube.com/watch?v=a39wb5YhZ5Q', downLink: '[Blank]' },
{ name: 'dead by daylight', image: '../assets/images/deadbydaylight.jpeg', storage: '25 GB', desc: 'Dead by Daylight is an asymmetric survival horror game developed by Behaviour Interactive. Players can take on the role of a survivor trying to escape a killer-controlled environment or play as the killer hunting down the survivors.', trailerLink: 'https://www.youtube.com/watch?v=Cj13S4jTc9w', downLink: '[Blank]' },
{ name: 'escape from tarkov', image: '../assets/images/escapefrom.jpeg', storage: '12 GB', desc: 'Escape from Tarkov is a hardcore and realistic online first-person action RPG/Simulator with MMO features and a story-driven walkthrough. Developed by Battlestate Games, players engage in raids in a fictional Russian city torn by warfare.', trailerLink: 'https://www.youtube.com/watch?v=-gj6u7o3QXM', downLink: '[Blank]' },
{ name: 'resident evil village', image: '../assets/images/residentevil.jpeg', storage: '50 GB', desc: 'Resident Evil Village is a survival horror game developed and published by Capcom. It is the tenth major installment in the Resident Evil series, following the story of Ethan Winters as he explores a mysterious village full of grotesque creatures.', trailerLink: 'https://www.youtube.com/watch?v=dRpXEc-EJow', downLink: '[Blank]' },
{ name: 'playerunknown\'s battlegrounds', image: '../assets/images/pubg.jpeg', storage: '30 GB', desc: 'PlayerUnknown\'s Battlegrounds is an online multiplayer battle royale game developed and published by PUBG Corporation. It features up to 100 players parachuting onto an island, scavenging for weapons and equipment to kill others while avoiding getting killed themselves.', trailerLink: 'https://www.youtube.com/watch?v=8yciuwzYb9I', downLink: '[Blank]' },
{ name: 'tom clancy\'s ghost recon breakpoint', image: '../assets/images/tomclancy.jpeg', storage: '50 GB', desc: 'Tom Clancy\'s Ghost Recon Breakpoint is a tactical shooter video game developed by Ubisoft Paris and published by Ubisoft. It is the eleventh installment in the Tom Clancy\'s Ghost Recon franchise and is set in an open-world environment called Auroa.', trailerLink: 'https://www.youtube.com/watch?v=j5yNvcJhrV0', downLink: '[Blank]' },
{ name: 'rust', image: '../assets/images/rust.jpeg', storage: '20 GB', desc: 'Rust is a multiplayer online survival game developed by Facepunch Studios. Players must survive by gathering resources, crafting items, and building shelters while avoiding being killed by other players and hostile creatures.', trailerLink: 'https://www.youtube.com/watch?v=4WTO2xKtomo', downLink: '[Blank]' },
{ name: 'the division 2', image: '../assets/images/thedivision.jpg', storage: '50 GB', desc: 'Tom Clancy\'s The Division 2 is an online action role-playing video game developed by Massive Entertainment and published by Ubisoft. Set in a near-future Washington, D.C., players take on the role of Division agents tasked with helping to rebuild the city after a biological attack.', trailerLink: 'https://www.youtube.com/watch?v=LrhaYSb_qP8', downLink: '[Blank]' },
];